services:
  get-work-platform-wa:
    image: get-work-platform-wa:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

